### ISSUE TITLE
I encountered errors downloading the dataset and pre training model.

### ISSUE THREAD

**Issue by Suelence-hu** [lzhengning/SubdivNet#10]
![image](https://user-images.githubusercontent.com/39931365/126057481-66abdf92-414a-4016-8b21-bbcd99a96c94.png)
I would appreciate it if you could help me！

**Comment by lzhengning** [comment]
@Suelence-hu ,

This seems to be a network issue. If wget do not work, you can manually download the dataset using the provided url. Then unzip it and move it to a `data` directory under the root path.
