### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by tt-study** [lzhengning/SubdivNet#11]
Why does each sample in the 'cubes' dataset have 10 subdivision samples in the 'Cubes-MAPS-48-4'? Are all the 10 subdivision samples trained as training samples?  Thank you

**Comment by lzhengning** [comment]
Hi, @tt-study ,

> Why does each sample in the 'cubes' dataset have 10 subdivision samples in the 'Cubes-MAPS-48-4'

Because randomness is introduced in the MAPS algorithm, for different remeshing of a shape. We generated multiple subdivision samples, as a way of data augmentation. This is effective when the training dataset is small.

> Are all the 10 subdivision samples trained as training samples.

Yes.
