### ISSUE TITLE
Could proposed method extend to unclosed mesh？

### ISSUE THREAD

**Issue by fh1999** [lzhengning/SubdivNet#14]
Hi @lzhengning ,thanks for opening the code. The proposed method worked fine on those dataset, however many meshes generated by algorithms like 3d visual reconstruction and lidar are usually unclosed. I am wondering is there any method could extend this work to unclosed meshes.

**Comment by lzhengning** [comment]
Hi, @fh1999, 

We are also thinking about this extension, :-). 

One possible way is to improve the remeshing algorithm to support boundary. Another thing is to add padding in the convolution. Though we are doing some experiments, it still takes some time to update this repo with support for unclosed mesh. 

If you have better ideas, welcome to have a discussion!
