### ISSUE TITLE
关于分割的对比实验结果

### ISSUE THREAD

**Issue by liang3588** [lzhengning/SubdivNet#15]
您好，我对分割的对比实验结果有一些疑问。
这是您文章中的结果
![image](https://user-images.githubusercontent.com/82434236/127609000-abedd64f-325e-45de-929e-abe050879cf2.png)
这是MeshCNN中给出的结果
![image](https://user-images.githubusercontent.com/82434236/127609074-f7e86c47-2ffe-4bf0-a608-2227d2997811.png)
我想问您给出的MeshCNN的结果和原有结果之间为什么会差距这么大呢？是经过了什么处理呢？

**Comment by lzhengning** [comment]
Hi, @liang3588,

我们采取的评价指标是和 COSEG 数据集的原始标注对应的，即计算面的分类正确与否。而 MeshCNN 的论文采取了不同的评价指标，即首先对 COSEG 的模型简化，再计算边的准确率：边的任一端点符合预测结果则该边算作预测正确。因此在 MeshCNN 文章使用的评价方法是相对较宽松的，正确率也会更高。

我们在论文 5.2 节中详细描述了如何用原数据集指标去评估各个方法的预测结果。在附录 C 中，我们也用 MeshCNN 的评价方法评估了 SubdivNet。

如果上述信息没有解答您的问题，欢迎回复讨论。

**Comment by liang3588** [comment]
好的，我明白了
那我还想问一个问题，您提供的分割数据集中，一个数据提供10个模型，（例如coseg_alien中，有1-000，1-001，1-002，... ,1-009）这几个模型之间的区别是什么呢？为什么要对一个数据提供10个模型呢？
谢谢！

**Comment by liang3588** [comment]
您的这10个模型是为了data augmentation么？

**Comment by lzhengning** [comment]
> 您的这10个模型是为了data augmentation么？

是的。这种 augmentation 的目的是让网络关注具体的形状，而对形状之上的网格顶点分布、连接关系不敏感。

**Comment by liang3588** [comment]
好的，谢谢

**Comment by liang3588** [comment]
我还有一个问题，您的分割数据集中一个mesh有16384个面，您有用过小一些的mesh做过分割实验么？因为我想和您的算法进行对比，但是数据集无法对齐，您提供的数据集中mesh太大了。

**Comment by liang3588** [comment]
还有一个问题是在您的文章中”Another issue is the lack of an agreed evaluation metric. Both PD-MeshNet [Milano et al. 2020] and MeshCNN [Hanocka et al. 2019] are evaluated over simplified meshes, and MeshCNN reports the accuracy on edges. For a fair comparison, we project their predictions back to the raw meshes as well. Specifically, to transfer the results of MeshCNN to faces in the raw mesh, we first find the nearest triangle to its face center in the simplified mesh, and take the label of the nearest edge in the triangle as the prediction.“这一段中我想知道您是用了MeshCNN提供的数据集，然后把结果映射回raw mesh么？
![image](https://user-images.githubusercontent.com/82434236/127952102-53596422-ac94-4510-87e1-2dc7ac4681b1.png)
也就是说在Table 4中，MeshCNN这个结果用的是有1500个面的mesh，而MeshCNN(10000 faces）用的是有10000个面的mesh么？那我很好奇为什么MeshCNN(10000 faces）反而要比MeshCNN的结果低那么多呢？

**Comment by lzhengning** [comment]
> 我还有一个问题，您的分割数据集中一个mesh有16384个面，您有用过小一些的mesh做过分割实验么？因为我想和您的算法进行对比，但是数据集无法对齐，您提供的数据集中mesh太大了。

目前没有试过更小的面数，因为分割的时候，参考了图像分割的网络设计，设置base size是256，设置3层细分结构就是16384。

**Comment by lzhengning** [comment]
> 还有一个问题是在您的文章中”Another issue is the lack of an agreed evaluation metric. Both PD-MeshNet [Milano et al. 2020] and MeshCNN [Hanocka et al. 2019] are evaluated over simplified meshes, and MeshCNN reports the accuracy on edges. For a fair comparison, we project their predictions back to the raw meshes as well. Specifically, to transfer the results of MeshCNN to faces in the raw mesh, we first find the nearest triangle to its face center in the simplified mesh, and take the label of the nearest edge in the triangle as the prediction.“这一段中我想知道您是用了MeshCNN提供的数据集，然后把结果映射回raw mesh么？
> ![image](https://user-images.githubusercontent.com/82434236/127952102-53596422-ac94-4510-87e1-2dc7ac4681b1.png)
> 也就是说在Table 4中，MeshCNN这个结果用的是有1500个面的mesh，而MeshCNN(10000 faces）用的是有10000个面的mesh么？那我很好奇为什么MeshCNN(10000 faces）反而要比MeshCNN的结果低那么多呢？

感觉原因是因为面变多后，卷积感受野相对变得更小了，对全局信息的捕捉能力变差，学习也更困难。

**Comment by liang3588** [comment]
![image](https://user-images.githubusercontent.com/82434236/128012569-9a8de9eb-cf73-4345-bb73-1ce4198a1b6e.png)
那表5中MeshCNN的结果是用多少个面片得到的啊？

**Comment by liang3588** [comment]
还有，您在表10中提到MeshCNN中数据大小是10000个面片，
![image](https://user-images.githubusercontent.com/82434236/128021074-67fa7c29-979e-4be2-a078-b7c40a5ca2fa.png)
我不清楚，这个10000个面片是指哪个实验中用的10000个面片啊？

**Comment by lzhengning** [comment]
> ![image](https://user-images.githubusercontent.com/82434236/128012569-9a8de9eb-cf73-4345-bb73-1ce4198a1b6e.png)
> 那表5中MeshCNN的结果是用多少个面片得到的啊？

这个表和其他的实验中，没有标明输入面片数量，都是使用 MeshCNN 原论文的配置。

> 还有，您在表10中提到MeshCNN中数据大小是10000个面片，
> ![image](https://user-images.githubusercontent.com/82434236/128021074-67fa7c29-979e-4be2-a078-b7c40a5ca2fa.png)
> 我不清楚，这个10000个面片是指哪个实验中用的10000个面片啊？

表10上，MeshCNN 10000 个面片是以人体分割实验为基础的，表10对比的都是分割方法的计算时间和存储消耗。

**Comment by liang3588** [comment]
> > ![image](https://user-images.githubusercontent.com/82434236/128012569-9a8de9eb-cf73-4345-bb73-1ce4198a1b6e.png)
> > 那表5中MeshCNN的结果是用多少个面片得到的啊？
> 
> 这个表和其他的实验中，没有标明输入面片数量，都是使用 MeshCNN 原论文的配置。
> 
> > 还有，您在表10中提到MeshCNN中数据大小是10000个面片，
> > ![image](https://user-images.githubusercontent.com/82434236/128021074-67fa7c29-979e-4be2-a078-b7c40a5ca2fa.png)
> > 我不清楚，这个10000个面片是指哪个实验中用的10000个面片啊？
> 
> 表10上，MeshCNN 10000 个面片是以人体分割实验为基础的，表10对比的都是分割方法的计算时间和存储消耗。

那在coseg分割实验中，SubdivNet用的输入模型是16384个面片的是么？

**Comment by lzhengning** [comment]
是的。在 coseg alien 里，SubdivNet 会把模型 remesh 成 base size 是 256，细分深度是 3，共 16384 个面。
