### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by tky135** [lzhengning/SubdivNet#17]
Hi, a few questions regarding preprocessing for segmentation:

1. How do you get sub_labels? Do you project the faces onto raw data? Is there any manual work involved in this process? 
2. When you reported your accuracies, whose labels did you use as the ground truth? The labels in the remeshed data or the raw data? 

Thanks.

**Comment by lzhengning** [comment]
Hi @tky135 ,

> How do you get sub_labels? 

sub_labels is obtained by projection labels on the raw mesh to the remeshed. The implementation is described [here](https://github.com/lzhengning/SubdivNet/issues/9#issuecomment-885535277).

> Do you project the faces onto raw data? 

Yes, the segmentation results on the remeshed are all projected to the raw data. The reported accuracy is also calculated on the raw data.

> Is there any manual work involved in this process?

No manually mapping is needed.

> When you reported your accuracies, whose labels did you use as the ground truth? The labels in the remeshed data or the raw data?

The ground truth is the per face labels on the raw data.

**Comment by tky135** [comment]
Thanks for your reply.
