### ISSUE TITLE
Where is datagen_maps.py

### ISSUE THREAD

**Issue by tomguluson92** [lzhengning/SubdivNet#2]
Hi,
    I am really impressed by your work. I want to test it on my own dataset where I did not found
`datagen_maps.py`. 

   Could you please provide it? Thank you so much!

**Comment by lzhengning** [comment]
Sorry about the mistake. I've uploaded the related scripts, and now you can have a try.

**Comment by tomguluson92** [comment]
> Sorry about the mistake. I've uploaded the related scripts, and now you can have a try.

Thank you very much!
