### ISSUE TITLE
question about visualization 

### ISSUE THREAD

**Issue by flyKite1998** [lzhengning/SubdivNet#21]
hi, thanks for your work. Can MeshTensor be visualized ? How can i get the model after pooling or convolution like Fig.1 in your paper?

**Comment by lzhengning** [comment]
Sure. MeshTensor has an attribute `faces` that stores the index of vertices in `M0` (the mesh that is not pooled). So you can use the vertices of `M0` and `some_mesh_tensor.faces` to visualize a mesh. 

The python code may be like

``` python
batch_vertices, batch_faces = load_mesh_func(...)
... # calculate features and pack them to MeshTensor
pooled_mesh = net(mesh)
pooled_faces = pooled_mesh.faces[0, :pooled_mesh.Fs[0]]
pooled_faces = pooled_faces.data # Jittor Var to Numpy array
vertices = batch_vertices[0]
trimesh.Trimesh(vertices, faces).export('my_mesh.obj')
```

**Comment by flyKite1998** [comment]
I understand，thanks a lot.
