### ISSUE TITLE
question about the input data "meshes"

### ISSUE THREAD

**Issue by amiltonwong** [lzhengning/SubdivNet#26]
Hi, @lzhengning ,

According to data loading from [here](https://github.com/lzhengning/SubdivNet/blob/master/train_seg.py#L31), meshes['faces']:(bs, num_f, 3), meshes['feats']:(bs, 13, num_f), meshes['Fs']:(bs,) are used for training iteration. Could you elaborate what those 13 channels mean in meshes['feats']?

Thanks

**Comment by lzhengning** [comment]
Hi @amiltonwong ,

The 13-channel input features are:

1. 7-dimensional **shape descriptor**: the face area, the three interior angles of the triangle, and the inner products of the face normal with the three vertex normals (characterizing curvature). 
2. 6-dimensional **pose descriptor**: the position of the face center and the face normal.

The implementation is the following function:
https://github.com/lzhengning/SubdivNet/blob/3c56f9fe8edf08b16fe015ad09684f8ced78a51d/subdivnet/dataset.py#L43
