### ISSUE TITLE
A PyTorch implementation of SubdivNet?

### ISSUE THREAD

**Issue by FuHui-UPC** [lzhengning/SubdivNet#33]
Thank you for your work. 
I want to ask if you have implemented the SubdivNet with **pytorch** ? Thanks again.

**Comment by lzhengning** [comment]
Hi, @FuHui-UPC,

There is no planning to develop a PyTorch version of SubdivNet. However, the core implementations could be reused  if you want to write a PyTorch extension (mostly in mesh_ops.py and mesh_tensor.py).
