### ISSUE TITLE
[/mnt/disk/lzn/SubdivDataset/HumanSeg-256-aug10]

### ISSUE THREAD

**Issue by tomguluson92** [lzhengning/SubdivNet#4]
Dear author, 
        I am eager to know if `HumanSeg-256-aug10` is available now? 
I don't found any clues except for `HumanBody-NS-256-3`. So could you please provide it for testing? 
       Really appreciated! Thank you!

**Comment by lzhengning** [comment]
`HumanSeg-256-aug10` is just an alias of `HumanBody-NS-256-3`. I will remove these codes to resolve misunderstanding.
