### ISSUE TITLE
reshape size error while training

### ISSUE THREAD

**Issue by MgGa-zzz** [lzhengning/SubdivNet#5]
Dear author, can you give me some advice about the following errors?

`/home/success/.conda/envs/subdiv2/bin/python /home/success/MgGa/upsampling/SubdivNet-master/train_cls.py train --name manifold40 --dataroot ./data/Manifold40/ --optim adam --lr 1e-3 --lr_milestones 20 40 --batch_size 48 --n_classes 40 --depth 3 --channels 32 64 128 256 --n_dropout 2 --use_xyz --use_normal --augment_scale
[i 0621 20:52:43.235719 56 compiler.py:858] Jittor(1.2.3.34) src: /home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor
[i 0621 20:52:43.237901 56 compiler.py:859] g++ at /usr/bin/g++(5.5.0)
[i 0621 20:52:43.237963 56 compiler.py:860] cache_path: /home/success/.cache/jittor/default/g++
[i 0621 20:52:43.240509 56 __init__.py:258] Found nvcc(10.0.130) at /usr/local/cuda/bin/nvcc.
[i 0621 20:52:43.283449 56 __init__.py:258] Found gdb(8.1.1) at /usr/bin/gdb.
[i 0621 20:52:43.285706 56 __init__.py:258] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0621 20:52:43.296301 56 compiler.py:919] py_include: -I/home/success/.conda/envs/subdiv2/include/python3.7m -I/home/success/.conda/envs/subdiv2/include/python3.7m
[i 0621 20:52:43.307131 56 compiler.py:921] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 0621 20:52:43.427413 56 compiler.py:1044] OS type:ubuntu OS key:ubuntu
[i 0621 20:52:43.428020 56 __init__.py:169] Total mem: 31.23GB, using 10 procs for compiling.
Compiling jittor_core(144/144) used: 27.395s eta: 0.000s
[i 0621 20:53:11.122010 56 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
[i 0621 20:53:11.122200 56 init.cc:55] Found cuda archs: [61,]
[i 0621 20:53:11.217410 56 __init__.py:258] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0621 20:53:11.234022 56 compiler.py:660] handle pyjt_include/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/extern/mpi/inc/mpi_warper.h
[i 0621 20:53:12.588011 56 compile_extern.py:337] Downloading nccl...
Compiling gen_ops_mkl_conv_backward_x_mkl_test_mkl_matmul_mkl_conv_mkl_conv_backward_w(7/7) used: 2.288s eta: 0.000s
[i 0621 20:53:18.678607 56 compile_extern.py:19] found /usr/local/cuda/include/cublas.h
[i 0621 20:53:18.682890 56 compile_extern.py:19] found /usr/local/cuda/lib64/libcublas.so
[i 0621 20:53:18.682977 56 compile_extern.py:19] found /usr/lib/x86_64-linux-gnu/libcublasLt.so.10
[i 0621 20:53:20.146853 56 compile_extern.py:19] found /usr/include/cudnn.h
[i 0621 20:53:20.153544 56 compile_extern.py:19] found /usr/lib/x86_64-linux-gnu/libcudnn.so
[i 0621 20:53:20.164575 56 compiler.py:660] handle pyjt_include/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h
Compiling gen_ops_cudnn_test_cudnn_conv3d_backward_w_cudnn_conv_cudnn_conv3d_cudnn_conv_ba___hash8356939239020823193(12/12) used: 2.907s eta: 0.000s
[i 0621 20:53:23.476182 56 compile_extern.py:19] found /usr/local/cuda/include/curand.h
[i 0621 20:53:23.487781 56 compile_extern.py:19] found /usr/local/cuda/lib64/libcurand.so
[i 0621 20:53:24.373308 56 cuda_flags.cc:26] CUDA enabled.
name:  manifold40
Train 0:   0%|          | 0/206 [00:00<?, ?it/s]
Compiling Operators(1/1) used: 2.21s eta:    0s 

Compiling Operators(1/1) used: 2.12s eta:    0s 

Compiling Operators(1/1) used: 2.08s eta:    0s 
Train 0:   0%|          | 0/206 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/home/success/MgGa/upsampling/SubdivNet-master/train_cls.py", line 185, in <module>
    train(net, optim, train_dataset, writer, epoch)
  File "/home/success/MgGa/upsampling/SubdivNet-master/train_cls.py", line 36, in train
    outputs = net(mesh_tensor)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/network.py", line 177, in execute
    mesh = self.convs(mesh)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/nn.py", line 1541, in execute
    x = layer(x)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/network.py", line 29, in execute
    mesh = self.mconv1(mesh)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/mesh_ops.py", line 53, in execute
    CKP = mesh_tensor.convolution_kernel_pattern(self.kernel_size, self.dilation)
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/mesh_tensor.py", line 409, in convolution_kernel_pattern
    return self.FAF
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/mesh_tensor.py", line 107, in FAF
    self._cache['FAF'] = self.compute_face_adjacency_faces()
  File "/home/success/MgGa/upsampling/SubdivNet-master/subdivnet/mesh_tensor.py", line 304, in compute_face_adjacency_faces
    S = S.reshape(-1, 2)
  File "/home/success/.conda/envs/subdiv2/lib/python3.7/site-packages/jittor/__init__.py", line 347, in reshape
    return origin_reshape(x, shape)
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.ops.reshape)).

Types of your inputs are:
 self	= module,
 args	= (Var, tuple, ),

The function declarations are:
 VarHolder* reshape(VarHolder* x,  NanoVector shape)

Failed reason:[f 0621 20:53:33.515809 56 reshape_op.cc:48] Check failed: y_items != 0 && x_items % y_items == 0  reshape shape is invalid for input of size  375

Process finished with exit code 1`

**Comment by lzhengning** [comment]
Are the Manifold40 dataset used to train the network? Manifold40 is just a repaired version of ModelNet40. It does not have subdivision connectivity, and thus cannot be used to train SubdivNet directly.

The preprocessed Manifold 40 which has subdivision connectivity can be downloaded through `scripts/manifold40/get_data.sh`.

**Comment by MgGa-zzz** [comment]
> Are the Manifold40 dataset used to train the network? Manifold40 is just a repaired version of ModelNet40. It does not have subdivision connectivity, and thus cannot be used to train SubdivNet directly.
> 
> The preprocessed Manifold 40 which has subdivision connectivity can be downloaded through `scripts/manifold40/get_data.sh
